package com.aswatson.sso.data.constant;

public enum ResponseCode {

    /**
     * Format : ETMMCCC
     * E : HardCode value
     * T : Error Type
     * 1 : validation, 2 : Logic handling, 5 : Server unhandled error
     * M : Module
     * C : Error Code
     */

    // System Generic error code E5*****
    SERVER_ERROR("SSO500000", "Internal Server Error."),
    JDBC_CONNECT_ERROR("SSO500001", "Internal Server Error."),

    // System Generic error code SSO10****
    VALIDATION_CLIENT_SECRET_NOT_VALID("SSO100000", "The client secret is invalid"),
    VALIDATION_AUTH_CODE_NOT_VALID("SSO100001", "The authentication code is expired or invalid"),
    VALIDATION_QR_TOKEN_NOT_VALID("SSO100002", "The QR token is expired or invalid"),
    VALIDATION_BUID_NOT_VALID("SSO100003", "The business unit id is not exist or disabled"),
    VALIDATION_REQUEST_BODY_NOT_NULLABLE("SSO100004", "Request body can not be null"),
    VALIDATION_QR_BUID_NOT_VALID("SSO100005", "QR code generated by BU is not found in Redis cache"),
    VALIDATION_REACT_IFRAME_PARENT_DOMAIN_NOT_VALID("SSO100006", "React Iframe parent domain is invalid"),

    // System Generic error code SSO11****
    VALIDATION_FIELD_QRCODE_NOT_VALID("SSO110000", "Field qrCode can not be null"),
    VALIDATION_FIELD_MBID_NOT_VALID("SSO110002", "Field mbId can not be null"),
    VALIDATION_FIELD_AUTH_CODE_NOT_VALID("SSO110003", "Field authenticationCode can not be null"),
    VALIDATION_FIELD_CLIENT_SECRET_NOT_VALID("SSO110004", "Field clientSecret can not be null"),
    VALIDATION_FIELD_PARENT_ORIGIN_NOT_VALID("SSO110005", "Field parentOrigin can not be null"),
    // System Generic error code SSO20****
    SESSION_NOT_FOUND_ERROR("SSO200000", "The Session is closed");

    //

    public final String code;
    public final String description;

    ResponseCode(String code, String description) {
        this.code = code;
        this.description = description;
    }
}
